### ISSUE TITLE
Next exercise?

### ISSUE THREAD

**Issue by Expecho** [Softwarepark/exercises#57]
I really love the way you set this whole DDD exercise up. That said, how about exercise 4, is it still in the pipeline?

**Comment by abdullin** [comment]
@Expecho, thank you for the kind words. Exercises 4 and 5 are still in the pipeline. 

I don't want to promise anything, but I'm working on getting the 4th done. 3rd one wasn't polished enough to be engaging, so I don't want to repeat the same mistake.

There will be a newsletter update when the next exercise is out.
