### ISSUE TITLE
Could you please provide access to discussions?

### ISSUE THREAD

**Issue by dadhich** [Softwarepark/exercises#67]
Hi, I am trying to learn DDD and would like to access discussions for same please? Many thanks!

**Comment by abdullin** [comment]
Sure, done. There aren't many recent discussions there, though.

I wonder, if discord would be more fun.

**Comment by dadhich** [comment]
Great, thanks, yes sure would love to join if there is a discord. 

On the discussions, when I click on the link ([Github discussions](https://github.com/orgs/ddd-exercises/teams/tt/discussions)), it gives me a 404. Is that the right link? 

Thanks again for the quick help!

**Comment by abdullin** [comment]
@dadhich the link is correct. It _should_ be visible for you. Strange :(

<img width="1032" alt="image" src="https://user-images.githubusercontent.com/504782/148968954-10317e27-ef0d-4704-a0f6-69f2530623dc.png">

**Comment by abdullin** [comment]
@dadhich here is the invite link. You'll be the first one to try it out :)

https://discord.gg/jHGbUwxDgv
